### ISSUE TITLE
can't find g2o/types/data/robot_odom.h and cause fatal error

### ISSUE THREAD

**Issue by upsetzju** [doomzzju/CSO#1]
hi,
thanks for your great work.
but g2o/types/data/robot_odom.h will be needed by CSO/include/libviso2_wrapper.h, CSO/include/gm2dl_io.h. I can't find it.
could you update this file?

thanks.

**Comment by doomzzju** [comment]
Hi,
thank you for noticing this ugly code~ You can find the missing files in the g2o example. One more issue, this job does not perform well.

**Comment by upsetzju** [comment]
ok, thanks for your quick response!
